version: '3.8'

services:
  db:
    image: postgres
    container_name: rpd-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rpdapi
